const Card3 = () => {
  return (
    <div className="container">
      <div className="has-text-light is-size-5">
        <p className="title has-text-success"> Film Farm</p>
        <ul>
          <li>A basic web application used to look up and compare movies.</li>
          <li>Fetches data from OMDb API and renders detailed information to end users.</li>
          <li>Displays films when searched side by side and compares key statistics available online </li>
          <li>Built on Javascript, HTML and CSS.</li>
        </ul>
        <br />
        <p className="subtitle is-size-4 has-text-ash"><b>Key Functions</b></p>
        <ul>
          <li>Renders: search result with some queried content displaying key information</li>
          <li>API keygen: calls and fetches data with OMDb API key already generated by gicodes</li>
          <li>Key Dependencies: debounce and autocomplete on keypress is critical to user experience.</li>
        </ul><br/>      
        <span><b>Source:</b> <a href="https://github.com/gicodes/film-farm">https://github.com/gicodes/film-farm</a></span>
      </div>
    </div>
  )
}

export default Card3;